### ISSUE TITLE
Pushing effect commands has no effect

### ISSUE THREAD

**Issue by GitGhillie** [SolarLiner/bevy-kira-components#1]
In the `interactive` example `update_track_panning` does not seem to work. Is this a known issue?

Apologies if I'm jumping the gun here, I know you haven't really published this crate yet. But having used only `kira` before and not `bevy_kira_audio` this crate seems a lot more intuitive to me. My goal is to use it to demonstrate some custom `kira` effects.

**Comment by GitGhillie** [comment]
I see the issue now and I was able to work around it, but it isn't pretty. Tough one...

**Comment by SolarLiner** [comment]
I removed the integrations of Kira's tracks before releasing, and somehow didn't see you had added the issue. It's because I've had to rack my brain to balance having a nice API to work with and actually being able to implement the API, and haven't found a good solution yet. Soon!
