### ISSUE TITLE
Missing .toggle() functionality

### ISSUE THREAD

**Issue by GitGhillie** [SolarLiner/bevy-kira-components#4]
Like in this example: https://github.com/bevyengine/bevy/blob/abddbf2d95ab3b0c37acfb11b34a9f323772fad1/examples/audio/audio_control.rs#L38

**Comment by SolarLiner** [comment]
I guess it could be added for API parity; however the [playback state](https://docs.rs/kira/latest/kira/sound/enum.PlaybackState.html) in Kira is a bit more complex than rodio, where it explicitely distinguishes between play/pause, *as well as* stopped (meaning, cannot be played again). This means that a `.toggle()` implementation would be fallible, and either be a no-op (with a log entry on failure), or returning a `Result<(), Error>` that needs to be handled in user code.

Further more, there are specific states for playback transitioning from one state to the other, as Kira uses tweens to fade audio in and out, and this means the transition could go either way -- do we force a decision then, or have it handled as another possible failure case?

For these reasons I'm leaning towards having the user make explicit choices themselves based on the playback state above. An example implementation could look like this:

```rust
fn toggle_sound(handle: &AudioFileHandle) {
    match handle.playback_state() {
        PlaybackState::Playing => handle.pause(),
        PlaybackState::Paused => handle.play(),
        // User choice: log error out when sound is stopped
        PlaybackState::Stopped => error!("Cannot resume stopped sound"),
        // User choice: no-op during transitions, because that means
        // another action has been taken recently.
        PlaybackState::Pausing | PlaybackState::Stopping => {},
    }
}
```

**Comment by GitGhillie** [comment]
Yeah personally I don't care that much about having the toggle function but I think it will make upstreaming easier, and makes the migration guide easier to write.

If we do implement this we can also see it as providing the user with a nice default. They can always implement their own toggle function if they want to / need to.

I would do `PlaybackState::Pausing => sink.resume()` though, it feels the most natural from my testing.
There's also precedent in Bevy for logging entries when the user makes a mistake (like having `Visibility::Inherented` on an entity whose parent does not have a `Visibility` component), so I think no-op + log entry is an ok solution.
